services:
  ingestion:
    build: ./MS1_ingestion
    volumes:
      - ./data:/app/data
    container_name: ingestion_microservice
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: btc_data

  storage:
    build: ./MS2_storage
    container_name: storage_microservice
    depends_on:
      - ingestion
      - postgres
      - minio
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btc_data
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MINIO_ENDPOINT: http://minio:9000
      BUCKET_NAME: btc-raw-data
    volumes:
      - ./data:/app/data
    entrypoint: ["./wait_for_postgres.sh"]
    command: ["python", "upload_to_minio.py"]

  preprocessing:
    build: ./MS3_Preprocessing
    container_name: preprocessing_microservice
    depends_on:
      - storage
      - postgres
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: btc-raw-data

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btc_data
    deploy:
      resources:
        limits:
          memory: 1g

  aggregation:
    build: ./MS4_aggregation
    container_name: aggregation_microservice
    depends_on:
      - preprocessing
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btc_data

  delivery:
    build: ./MS5_delivery
    container_name: delivery_microservice
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=btc_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  postgres:
    image: postgres:15
    container_name: btc_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btc_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: btc_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
