version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: btc_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btc_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  ingest:
    build:
      context: ./ingest
    container_name: btc_ingestor
    volumes:
      - ./raw_data:/app/raw_data
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: btc_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
